//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kcsara.Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberMedical
    {
        public System.Guid Id { get; set; }
        public string EncryptedAllergies { get; set; }
        public string EncryptedMedications { get; set; }
        public string EncryptedDisclosures { get; set; }
        public System.DateTime LastChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
