//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kcsara.Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.MemberEmergencyContacts = new HashSet<MemberEmergencyContact>();
            this.MemberUnitDocuments = new HashSet<MemberUnitDocument>();
            this.PersonAddresses = new HashSet<PersonAddress>();
            this.PersonContacts = new HashSet<PersonContact>();
            this.TrainingAwards = new HashSet<TrainingAward>();
            this.TrainingRosters = new HashSet<TrainingRoster>();
        }
    
        public System.Guid Id { get; set; }
        public string DEM { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> InternalBirthDate { get; set; }
        public string InternalGender { get; set; }
        public string PhotoFile { get; set; }
        public int InternalWacLevel { get; set; }
        public System.DateTime WacLevelDate { get; set; }
        public string Username { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> BackgroundDate { get; set; }
        public Nullable<System.DateTime> SheriffApp { get; set; }
        public Nullable<int> ExternalKey1 { get; set; }
        public int Status { get; set; }
        public System.DateTime LastChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual ICollection<MemberEmergencyContact> MemberEmergencyContacts { get; set; }
        public virtual MemberMedical MemberMedical { get; set; }
        public virtual ICollection<MemberUnitDocument> MemberUnitDocuments { get; set; }
        public virtual ICollection<PersonAddress> PersonAddresses { get; set; }
        public virtual ICollection<PersonContact> PersonContacts { get; set; }
        public virtual ICollection<TrainingAward> TrainingAwards { get; set; }
        public virtual ICollection<TrainingRoster> TrainingRosters { get; set; }
    }
}
