//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kcsara.Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberUnitDocument
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> MemberAction { get; set; }
        public Nullable<System.DateTime> UnitAction { get; set; }
        public int Status { get; set; }
        public System.DateTime LastChanged { get; set; }
        public string ChangedBy { get; set; }
        public System.Guid Member_Id { get; set; }
        public System.Guid Document_Id { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
