//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kcsara.Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonContact
    {
        public System.Guid Id { get; set; }
        public string Type { get; set; }
        public string Subtype { get; set; }
        public string Value { get; set; }
        public int Priority { get; set; }
        public System.DateTime LastChanged { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.Guid> Person_Id { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
