//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kcsara.Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonAddress
    {
        public System.Guid Id { get; set; }
        public string InternalType { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Geo { get; set; }
        public int Quality { get; set; }
        public int RosterVisibility { get; set; }
        public System.DateTime LastChanged { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.Guid> Person_Id { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
