//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kcsara.Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingRule
    {
        public TrainingRule()
        {
            this.TrainingAwards = new HashSet<TrainingAward>();
        }
    
        public System.Guid Id { get; set; }
        public string RuleText { get; set; }
        public Nullable<System.DateTime> OfferedFrom { get; set; }
        public Nullable<System.DateTime> OfferedUntil { get; set; }
        public System.DateTime LastChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual ICollection<TrainingAward> TrainingAwards { get; set; }
    }
}
