//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kcsara.Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public Training()
        {
            this.TrainingRosters = new HashSet<TrainingRoster>();
            this.TrainingCourses = new HashSet<TrainingCours>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string County { get; set; }
        public string StateNumber { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public Nullable<System.Guid> Previous { get; set; }
        public string Comments { get; set; }
        public string Location { get; set; }
        public System.DateTime LastChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual ICollection<TrainingRoster> TrainingRosters { get; set; }
        public virtual ICollection<TrainingCours> TrainingCourses { get; set; }
    }
}
