//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kcsara.Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingAward
    {
        public System.Guid Id { get; set; }
        public System.DateTime Completed { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public string DocPath { get; set; }
        public string metadata { get; set; }
        public System.DateTime LastChanged { get; set; }
        public string ChangedBy { get; set; }
        public System.Guid Member_Id { get; set; }
        public System.Guid Course_Id { get; set; }
        public Nullable<System.Guid> Roster_Id { get; set; }
        public Nullable<System.Guid> TrainingRule_Id { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual TrainingCours TrainingCours { get; set; }
        public virtual TrainingRoster TrainingRoster { get; set; }
        public virtual TrainingRule TrainingRule { get; set; }
    }
}
