//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kcsara.Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingCours
    {
        public TrainingCours()
        {
            this.TrainingAwards = new HashSet<TrainingAward>();
            this.Trainings = new HashSet<Training>();
        }
    
        public System.Guid Id { get; set; }
        public string DisplayName { get; set; }
        public string FullName { get; set; }
        public string Categories { get; set; }
        public int WacRequired { get; set; }
        public bool ShowOnCard { get; set; }
        public Nullable<int> ValidMonths { get; set; }
        public Nullable<System.DateTime> OfferedFrom { get; set; }
        public Nullable<System.DateTime> OfferedUntil { get; set; }
        public string Metadata { get; set; }
        public string PrerequisiteText { get; set; }
        public System.DateTime LastChanged { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.Guid> Unit_Id { get; set; }
    
        public virtual ICollection<TrainingAward> TrainingAwards { get; set; }
        public virtual ICollection<Training> Trainings { get; set; }
    }
}
